sudo: required 

before_script:
  - bundle exec rails

addons:
  apt:
    sources:
    - google-chrome
  packages:
    - google-chrome-stable
cache: bundler
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rspec
  - bundle exec rake db:drop
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake
dist: xenial
