sudo: required 

before_script:
  - rake db:migrate bundle install exec rspec

addons:
  apt:
    sources:
    - google-chrome
  packages:
    - google-chrome-stable
cache: bundler
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rspec
dist: xenial
